site_name: rainbow mind machine
docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'red'
    accent: 'red'
  logo:
    icon: 'settings input component'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
markdown_extensions:
  - admonition
pages:
  - 'Home':         'index.md'
  - 'Installing':   'installing.md'
  - 'Quick Start':  'quickstart.md'
  - 'Docker':       'docker.md'
